### ISSUE TITLE
Curso de Linux da Geofisica

### ISSUE THREAD

**Issue by Isabela192** [iagdevs/Brainstorm#1]
Falei com o Leonardo da geo e ele disse que a geo vai oferecer o curso de Linux básico nessas férias acho que pela terceira vez.
Enfim, queria saber o que vcs acham de colocar esse curso no IAG devs, tipo, expandir as idéias

**Comment by Schuch666** [comment]
acho pode ser uma boa ideia, se não me engano o Jean tem uma apostila que ele fez para um curso de Linux

**Comment by rachelalbrecht** [comment]
Sergio, vc quer que eu convide o Bianchi para incluir o curso de Linux da
Geofísica no IAGdevs?

**Comment by ibarraespinosa** [comment]
Pode ser ne? Se voces acham que é bom, eu apoio. Eu acho que é uma boa ideia
